--DECLARE
--	counter NUMBER := 1;
BEGIN
	FOR i IN 1..10000 LOOP
		INSERT INTO MYTABLE m (val)
		VALUES (ROUND(DBMS_RANDOM.VALUE(1, 10000)));
--		counter := counter + 1;
	END LOOP;
	COMMIT;
END;

SELECT * FROM MYTABLE m ;

DROP TABLE MYTABLE ;
