CREATE OR REPLACE PROCEDURE Insert_Record(p_id NUMBER, p_val NUMBER) IS 
BEGIN 
	INSERT INTO MYTABLE (id, val) VALUES (p_id, p_val);
	COMMIT;
END;

CREATE OR REPLACE PROCEDURE Update_Record(p_id NUMBER, p_val NUMBER) IS 
BEGIN 
	UPDATE MYTABLE SET val = p_val WHERE id = p_id;
	COMMIT;
END;

CREATE OR REPLACE PROCEDURE Delete_Record(p_id NUMBER) IS 
BEGIN 
	DELETE FROM MYTABLE WHERE id = p_id;
	COMMIT;
END;


