-- Procedure to restore STUDENTS table state at a given timestamp or time offset
CREATE OR REPLACE PROCEDURE LAB.RESTORE_STUDENTS_STATE (
	p_timestamp TIMESTAMP,
	time_offset INTERVAL DAY TO SECOND DEFAULT NULL 
) IS 
	effective_time TIMESTAMP;
BEGIN
	IF time_offset IS NOT NULL THEN
		effective_time := SYSTIMESTAMP - time_offset;
	ELSE
		effective_time := p_timestamp;
	END IF;

	FOR lg IN (
		SELECT * FROM LAB.STUDENTS_LOG
		WHERE ACTION_TIMESTAMP >= effective_time
		ORDER BY ACTION_TIMESTAMP DESC 
	) LOOP 
		IF lg.ACTION_TYPE = 'INSERT' THEN
			DELETE FROM STUDENTS 
			WHERE STUDENT_ID = lg.STUDENT_ID;
		ELSIF lg.ACTION_TYPE = 'UPDATE' THEN 
			UPDATE STUDENTS
			SET NAME = lg.OLD_NAME,
				GROUP_ID = lg.OLD_GROUP_ID
			WHERE STUDENT_ID = lg.STUDENT_ID;
		ELSIF lg.ACTION_TYPE = 'DELETE' THEN 
			INSERT INTO STUDENTS (NAME, GROUP_ID)
			VALUES (lg.OLD_NAME, lg.OLD_GROUP_ID);
		END IF; 
	END LOOP;
END;

SELECT * FROM lab.STUDENTS_LOG sl ;
SELECT * FROM lab.STUDENTS;


CALL LAB.RESTORE_STUDENTS_STATE(TIMESTAMP '2025-02-24 12:24:32', NULL);
CALL LAB.RESTORE_STUDENTS_STATE(NULL, INTERVAL '0 01:00:00' DAY TO SECOND);
