-- Trigger for auto-incrementing ID in GROUPS
CREATE OR REPLACE TRIGGER TRG_GROUP_ID_AUTOINC
BEFORE INSERT ON LAB.GROUPS 
FOR EACH ROW 
BEGIN 
	IF :NEW.ID IS NULL THEN 
		SELECT group_id_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
	END IF;
END;

-- Trigger for auto-incrementing ID in STUDENTS
CREATE OR REPLACE TRIGGER TRG_STUDENT_ID_AUTOINC
BEFORE INSERT ON LAB.STUDENTS
FOR EACH ROW 
BEGIN 
	IF :NEW.STUDENT_ID IS NULL THEN 
		SELECT student_id_seq.NEXTVAL INTO :NEW.STUDENT_ID FROM DUAL;
	END IF;
END;

-- Trigger for enforcing uniqueness of GROUP.NAME
CREATE OR REPLACE TRIGGER TRG_GROUP_NAME_UNIQUE
BEFORE INSERT OR UPDATE ON LAB.GROUPS
FOR EACH ROW 
DECLARE 
	v_count NUMBER;
BEGIN 
	SELECT COUNT(*)
	INTO v_count
	FROM LAB.GROUPS
	WHERE LOWER(NAME) = LOWER(:NEW.NAME);

	IF v_count > 0 THEN
		RAISE_APPLICATION_ERROR(-20001, 'Group name must be unique');
	END IF;
END;

-- Trigger to enforce unique ID in GROUPS
CREATE OR REPLACE TRIGGER TRG_GROUP_ID_UNIQUE
BEFORE INSERT ON LAB.GROUPS
FOR EACH ROW 
DECLARE 
	v_count NUMBER;
BEGIN
	SELECT COUNT(*)
	INTO v_count
	FROM LAB.GROUPS
	WHERE ID = :NEW.ID;
	IF v_count > 0 THEN
		RAISE_APPLICATION_ERROR(-20002, 'Group ID must be unique');
	END IF;
END;

--Trigger to enforce unique STUDENT_ID in STUDENTS
CREATE OR REPLACE TRIGGER TRG_STUDENT_ID_UNIQUE
BEFORE INSERT ON LAB.STUDENTS
FOR EACH ROW 
DECLARE 
	v_count NUMBER;
BEGIN 
	SELECT COUNT(*)
	INTO v_count
	FROM LAB.STUDENTS WHERE STUDENT_ID = :NEW.STUDENT_ID;
	IF v_count > 0 THEN
		RAISE_APPLICATION_ERROR(-20003, 'Student ID must be unique');
	END IF;
END;






