-- Trigger for logging changes in STUDENTS
CREATE OR REPLACE TRIGGER TRG_STUDENTS_LOG
AFTER INSERT OR UPDATE OR DELETE ON LAB.STUDENTS
FOR EACH ROW 
BEGIN 
	IF INSERTING THEN 
		INSERT INTO LAB.STUDENTS_LOG (STUDENT_ID, ACTION_TYPE, NEW_NAME, NEW_GROUP_ID)
		VALUES (:NEW.STUDENT_ID, 'INSERT', :NEW.NAME, :NEW.GROUP_ID);
	ELSIF UPDATING THEN
		INSERT INTO LAB.STUDENTS_LOG (STUDENT_ID, ACTION_TYPE, OLD_NAME, NEW_NAME, OLD_GROUP_ID, NEW_GROUP_ID)
		VALUES (:OLD.STUDENT_ID, 'UPDATE', :OLD.NAME, :NEW.NAME, :OLD.GROUP_ID, :NEW.GROUP_ID);
	ELSIF DELETING THEN
		INSERT INTO LAB.STUDENTS_LOG (STUDENT_ID, ACTION_TYPE, OLD_NAME, OLD_GROUP_ID)
		VALUES (:OLD.STUDENT_ID, 'DELETE', :OLD.NAME, :OLD.GROUP_ID);
	END IF;
END;

SELECT * FROM LAB.STUDENTS_LOG;
