--Trigger for C_VAL update (add student)
CREATE OR REPLACE TRIGGER TRG_STUDENT_INSERT
AFTER INSERT ON LAB.STUDENTS
FOR EACH ROW 
BEGIN 
	UPDATE LAB.GROUPS
	SET C_VAL = C_VAL + 1
	WHERE ID = :NEW.GROUP_ID;
END;

--Trigger for C_VAL update (delete student)
CREATE OR REPLACE TRIGGER TRG_STUDENT_DELETE
AFTER DELETE ON LAB.STUDENTS
FOR EACH ROW 
BEGIN 
	UPDATE LAB.GROUPS 
	SET C_VAL = C_VAL - 1
	WHERE ID = :OLD.GROUP_ID;
END;

--Trigger for C_VAL update (when a student changes groups)
CREATE OR REPLACE TRIGGER TRG_STUDENT_UPDATE
AFTER UPDATE OF GROUP_ID ON LAB.STUDENTS
FOR EACH ROW 
BEGIN 
	--counter decrease at old group
	IF :OLD.GROUP_ID IS NOT NULL THEN 
		UPDATE LAB.GROUPS 
		SET C_VAL = C_VAL - 1
		WHERE ID = :OLD.GROUP_ID;
	END IF;
	
	--counter increase at new group
	IF :NEW.GROUP_ID IS NOT NULL THEN
		UPDATE LAB.GROUPS 
		SET C_VAL = C_VAL + 1
		WHERE ID = :NEW.GROUP_ID;
	END IF;
END;