-- Trigger for enforcing foreign key constraint manually
CREATE OR REPLACE TRIGGER TRG_STUDENT_GROUP_FK
BEFORE INSERT OR UPDATE ON LAB.STUDENTS
FOR EACH ROW 
DECLARE 
	v_count NUMBER;
BEGIN
	SELECT COUNT(*) INTO v_count FROM LAB.GROUPS WHERE ID = :NEW.GROUP_ID;
	IF v_count = 0 THEN
		RAISE_APPLICATION_ERROR(-20002, 'Group ID does not exist');
	END IF;
END;

-- Trigger for cascading delete on GROUPS
CREATE OR REPLACE TRIGGER TRG_GROUP_DELETE_CASCADE
BEFORE DELETE ON LAB.GROUPS
FOR EACH ROW 
BEGIN 
	DELETE FROM LAB.STUDENTS WHERE GROUP_ID = :OLD.ID;
END;

