INSERT INTO LAB.GROUPS g (NAME)
VALUES ('Test1');
INSERT INTO LAB.GROUPS g (NAME)
VALUES ('Test3');

SELECT * FROM LAB.GROUPS;
SELECT * FROM LAB.STUDENTS s ;

INSERT INTO LAB.STUDENTS s (NAME, GROUP_ID)
VALUES ('jkkf', 4);

INSERT INTO LAB.STUDENTS s (NAME, GROUP_ID)
VALUES ('zxc', 1);

ALTER TRIGGER TRG_GROUP_NAME_UNIQUE DISABLE;

DELETE FROM LAB.GROUPS
WHERE ID = 1;

DELETE FROM LAB.STUDENTS
WHERE STUDENT_ID = 11;

SELECT * FROM LAB.STUDENTS_LOG sl ;
SELECT * FROM LAB.GROUPS_LOG gl ;

CALL LAB.RESTORE_STUDENTS_STATE(TIMESTAMP '2025-03-02 22:03:00', NULL);
CALL LAB.RESTORE_STUDENTS_STATE(NULL, INTERVAL '0 01:00:00' DAY TO SECOND);
